import { defineConfig } from "tinacms";

const branch = process.env.HEAD || process.env.VERCEL_GIT_COMMIT_REF || "main";

export default defineConfig({
  branch,
  clientId: process.env.TINA_CLIENT_ID,
  token: process.env.TINA_TOKEN,

  build: {
    outputFolder: "admin",
    publicFolder: "src", // Ensure this matches your Eleventy input directory
  },
  media: {
    tina: {
      mediaRoot: "assets/assets/images",
      publicFolder: "src",
    },
  },
  schema: {
    collections: [
      {
        name: "blog",
        label: "Blog Posts",
        path: "src/blog/posts",
        format: "md",
        fields: [
          {
            type: "string",
            name: "title",
            label: "Title",
            isTitle: true,
            required: true,
          },
          {
            type: "string",
            name: "description",
            label: "Description",
            required: true,
          },
          {
            type: "datetime",
            name: "date",
            label: "Publication Date",
            required: true,
          },
          { type: "image", name: "image", label: "Featured Image" },
          { type: "string", name: "imageAlt", label: "Image Alt Text" },
          { type: "string", name: "tags", label: "Tags", list: true },
          { type: "boolean", name: "featured", label: "Featured Post" },
          { type: "rich-text", name: "body", label: "Body", isBody: true },
        ],
        ui: {
          // document._sys.filename is standard, but ensure your 11ty routes match
          router: ({ document }) => `/blog/${document._sys.filename}`,
        },
      },
      {
        name: "products",
        label: "Products",
        path: "src/shop/products",
        format: "md",
        fields: [
          {
            type: "string",
            name: "title",
            label: "Product Name",
            isTitle: true,
            required: true,
          },
          {
            type: "string",
            name: "description",
            label: "Short Description",
            required: true,
          },
          { type: "number", name: "price", label: "Price (€)", required: true },
          {
            type: "number",
            name: "originalPrice",
            label: "Original Price (€)",
          },
          { type: "string", name: "sku", label: "SKU", required: true },
          {
            type: "number",
            name: "stock",
            label: "Stock Quantity",
            required: true,
          },
          {
            type: "string",
            name: "category",
            label: "Category",
            options: [
              { label: "Electronics", value: "electronics" },
              { label: "Clothing", value: "clothing" },
              { label: "Home & Garden", value: "home-garden" },
              { label: "Sports", value: "sports" },
              { label: "Books", value: "books" },
            ],
            required: true,
          },
          {
            type: "image",
            name: "images",
            label: "Product Images",
            list: true,
          },
          { type: "boolean", name: "featured", label: "Featured Product" },
          {
            type: "boolean",
            name: "available",
            label: "Available for Purchase",
            required: true,
          },
          {
            type: "object",
            name: "specifications",
            label: "Specifications",
            list: true,
            fields: [
              { type: "string", name: "name", label: "Specification Name" },
              { type: "string", name: "value", label: "Value" },
            ],
          },
          {
            type: "rich-text",
            name: "body",
            label: "Detailed Description",
            isBody: true,
          },
        ],
        ui: {
          router: ({ document }) => `/shop/product/${document._sys.filename}`,
        },
      },
      {
        name: "site",
        label: "Site Settings",
        path: "src/_data",
        format: "json",
        // 'match' is deprecated in newer versions for 'ui.allowedActions' or specific paths.
        // I kept your fields but removed the 'match' property as it's usually inferred from 'path'
        ui: {
          allowedActions: {
            create: false,
            delete: false,
          },
        },
        fields: [
          {
            type: "string",
            name: "title",
            label: "Site Title",
            required: true,
          },
          {
            type: "string",
            name: "description",
            label: "Site Description",
            required: true,
          },
          { type: "string", name: "url", label: "Site URL", required: true },
          {
            type: "string",
            name: "lang",
            label: "Language",
            options: [
              { label: "English", value: "en" },
              { label: "Spanish", value: "es" },
              { label: "French", value: "fr" },
              { label: "German", value: "de" },
            ],
            required: true,
          },
          { type: "string", name: "author", label: "Author", required: true },
          { type: "image", name: "logo", label: "Site Logo" },
          {
            type: "object",
            name: "social",
            label: "Social Media Links",
            list: true,
            fields: [
              {
                type: "string",
                name: "name",
                label: "Platform Name",
                options: ["Facebook", "Twitter", "Instagram", "LinkedIn"],
              },
              { type: "string", name: "url", label: "URL" },
            ],
          },
          {
            type: "object",
            name: "contact",
            label: "Contact Information",
            fields: [
              { type: "string", name: "email", label: "Email" },
              { type: "string", name: "phone", label: "Phone" },
              { type: "string", name: "address", label: "Address" },
            ],
          },
          {
            type: "object",
            name: "ecommerce",
            label: "E-commerce Settings",
            fields: [
              {
                type: "string",
                name: "currency",
                label: "Currency",
                options: ["EUR", "USD", "GBP"],
              },
              {
                type: "number",
                name: "freeShippingThreshold",
                label: "Free Shipping Threshold",
              },
              {
                type: "number",
                name: "shippingCost",
                label: "Standard Shipping Cost",
              },
            ],
          },
        ],
      },
      {
        name: "visits",
        label: "Visites Page",
        path: "src/_data/visits",
        format: "json",
        ui: {
          allowedActions: {
            create: false,
            delete: false,
          },
        },
        fields: [
          {
            type: "object",
            name: "hero",
            label: "Hero",
            fields: [
              {
                type: "image",
                name: "image",
                label: "Hero Image",
                required: true,
              },
              {
                type: "string",
                name: "imageAlt",
                label: "Hero Image Alt Text",
                required: true,
              },
              {
                type: "string",
                name: "title",
                label: "Hero Title",
                required: true,
              },
              {
                type: "string",
                name: "text",
                label: "Hero Text",
                ui: { component: "textarea" },
                required: true,
              },
              {
                type: "string",
                name: "ctaLabel",
                label: "Hero Button Label",
                required: true,
              },
              {
                type: "string",
                name: "ctaHref",
                label: "Hero Button Link",
                required: true,
              },
            ],
          },
          {
            type: "object",
            name: "activitiesIntro",
            label: "Activities Intro",
            fields: [
              {
                type: "string",
                name: "title",
                label: "Title",
                required: true,
              },
              {
                type: "string",
                name: "text",
                label: "Text",
                ui: { component: "textarea" },
                required: true,
              },
            ],
          },
          {
            type: "object",
            name: "banner",
            label: "Bottom Banner",
            fields: [
              {
                type: "image",
                name: "image",
                label: "Background Image",
                required: true,
              },
              {
                type: "string",
                name: "imageAlt",
                label: "Background Image Alt Text",
                required: true,
              },
              {
                type: "string",
                name: "title",
                label: "Banner Title",
                required: true,
              },
              {
                type: "string",
                name: "text",
                label: "Banner Text",
                ui: { component: "textarea" },
                required: true,
              },
              {
                type: "string",
                name: "buttonLabel",
                label: "Button Label",
                required: true,
              },
              {
                type: "string",
                name: "buttonHref",
                label: "Button Link",
                required: true,
              },
            ],
          },
        ],
      },
      {
        name: "visitActivities",
        label: "Visit Activities",
        path: "src/visits/activities",
        format: "md",
        fields: [
          {
            type: "string",
            name: "title",
            label: "Title",
            isTitle: true,
            required: true,
          },
          {
            type: "number",
            name: "order",
            label: "Order",
            required: true,
          },
          {
            type: "string",
            name: "permalink",
            label: "Permalink",
            required: true,
          },
          {
            type: "image",
            name: "cardImage",
            label: "Card Image",
            required: true,
          },
          {
            type: "string",
            name: "cardImageAlt",
            label: "Card Image Alt Text",
            required: true,
          },
          {
            type: "string",
            name: "cardDescription",
            label: "Card Description",
            ui: { component: "textarea" },
            required: true,
          },
          {
            type: "image",
            name: "heroImage",
            label: "Hero Image",
            required: true,
          },
          {
            type: "string",
            name: "heroImageAlt",
            label: "Hero Image Alt Text",
            required: true,
          },
          {
            type: "string",
            name: "galleryButtonLabel",
            label: "Gallery Button Label",
            required: true,
          },
          {
            type: "string",
            name: "reservationPrompt",
            label: "Reservation Prompt",
            required: true,
          },
          {
            type: "string",
            name: "reservationPrimaryLabel",
            label: "Primary Reservation Button Label",
            required: true,
          },
          {
            type: "string",
            name: "reservationPrimaryLink",
            label: "Primary Reservation Button Link",
            required: true,
          },
          {
            type: "string",
            name: "whatsappLink",
            label: "WhatsApp Link",
          },
          {
            type: "string",
            name: "emailAddress",
            label: "Email Address",
          },
          {
            type: "string",
            name: "phoneNumber",
            label: "Phone Number",
          },
          {
            type: "string",
            name: "bookingHighlights",
            label: "Booking Highlights",
            list: true,
          },
          {
            type: "number",
            name: "personsMin",
            label: "Persons (Min)",
            required: true,
          },
          {
            type: "number",
            name: "personsMax",
            label: "Persons (Max)",
            required: true,
          },
          {
            type: "string",
            name: "duration",
            label: "Duration",
            required: true,
          },
          {
            type: "string",
            name: "priceFrom",
            label: "Price From",
            required: true,
          },
          {
            type: "string",
            name: "priceNote",
            label: "Price Note",
            required: true,
          },
          {
            type: "string",
            name: "difficulty",
            label: "Difficulty",
            required: true,
          },
          {
            type: "string",
            name: "kidFriendly",
            label: "Kid Friendly",
            required: true,
          },
          {
            type: "string",
            name: "languages",
            label: "Languages",
            required: true,
          },
          {
            type: "string",
            name: "overviewIntro",
            label: "Overview Intro",
            ui: { component: "textarea" },
            required: true,
          },
          {
            type: "object",
            name: "itinerary",
            label: "Itinerary",
            list: true,
            fields: [
              {
                type: "string",
                name: "time",
                label: "Time",
                required: true,
              },
              {
                type: "string",
                name: "title",
                label: "Title",
                required: true,
              },
              {
                type: "string",
                name: "description",
                label: "Description",
                ui: { component: "textarea" },
                required: true,
              },
            ],
          },
          {
            type: "object",
            name: "pricing",
            label: "Pricing",
            list: true,
            fields: [
              {
                type: "string",
                name: "group",
                label: "Group Size",
                required: true,
              },
              {
                type: "string",
                name: "price",
                label: "Price",
                required: true,
              },
            ],
          },
          {
            type: "string",
            name: "includedServices",
            label: "Included Services",
            ui: { component: "textarea" },
            required: true,
          },
          {
            type: "string",
            name: "meetingPoint",
            label: "Meeting Point",
            ui: { component: "textarea" },
            required: true,
          },
          {
            type: "string",
            name: "additionalInfo",
            label: "Additional Info",
            ui: { component: "textarea" },
            required: true,
          },
          {
            type: "object",
            name: "experienceHighlightsSection",
            label: "Adventure Highlights Section",
            fields: [
              {
                type: "string",
                name: "eyebrow",
                label: "Eyebrow",
                required: true,
              },
              {
                type: "string",
                name: "title",
                label: "Title",
                required: true,
              },
              {
                type: "string",
                name: "intro",
                label: "Intro",
                ui: { component: "textarea" },
                required: true,
              },
              {
                type: "object",
                name: "items",
                label: "Cards",
                list: true,
                fields: [
                  {
                    type: "string",
                    name: "title",
                    label: "Card Title",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "text",
                    label: "Card Text",
                    ui: { component: "textarea" },
                    required: true,
                  },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "reviewsSection",
            label: "Reviews Section",
            fields: [
              {
                type: "string",
                name: "eyebrow",
                label: "Eyebrow",
                required: true,
              },
              {
                type: "string",
                name: "title",
                label: "Title",
                required: true,
              },
              {
                type: "string",
                name: "ratingLabel",
                label: "Rating Label",
                required: true,
              },
              {
                type: "string",
                name: "ratingValue",
                label: "Rating Value",
                required: true,
              },
              {
                type: "string",
                name: "sourceLabel",
                label: "Source Label",
                required: true,
              },
              {
                type: "object",
                name: "reviews",
                label: "Reviews",
                list: true,
                fields: [
                  {
                    type: "string",
                    name: "quote",
                    label: "Quote",
                    ui: { component: "textarea" },
                    required: true,
                  },
                  {
                    type: "string",
                    name: "author",
                    label: "Author",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "date",
                    label: "Date",
                    required: true,
                  },
                  {
                    type: "image",
                    name: "avatar",
                    label: "Avatar",
                  },
                  {
                    type: "string",
                    name: "avatarAlt",
                    label: "Avatar Alt Text",
                  },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "gallery",
            label: "Gallery",
            list: true,
            fields: [
              {
                type: "image",
                name: "image",
                label: "Image",
                required: true,
              },
              {
                type: "string",
                name: "alt",
                label: "Image Alt Text",
                required: true,
              },
            ],
          },
          {
            type: "rich-text",
            name: "body",
            label: "General Description Body",
            isBody: true,
          },
        ],
        ui: {
          router: ({ document }) =>
            document?.permalink || `/visits/${document._sys.filename}/`,
        },
      },
      {
        name: "professionalsInspiration",
        label: "Professionals Inspiration",
        path: "src/_data/professionalsInspiration",
        format: "json",
        ui: {
          allowedActions: {
            create: false,
            delete: false,
          },
        },
        fields: [
          {
            type: "object",
            name: "hero",
            label: "Hero",
            fields: [
              { type: "string", name: "title", label: "Title", required: true },
              {
                type: "string",
                name: "text",
                label: "Text",
                ui: { component: "textarea" },
                required: true,
              },
              {
                type: "string",
                name: "ctaLabel",
                label: "CTA Label",
                required: true,
              },
              {
                type: "string",
                name: "ctaHref",
                label: "CTA Link",
                required: true,
              },
              {
                type: "image",
                name: "backgroundImage",
                label: "Background Image",
                required: true,
              },
              {
                type: "string",
                name: "backgroundAlt",
                label: "Background Alt Text",
                required: true,
              },
            ],
          },
          {
            type: "object",
            name: "foundationsSection",
            label: "Foundations Section",
            fields: [
              {
                type: "string",
                name: "title",
                label: "Section Title",
                required: true,
              },
              {
                type: "string",
                name: "intro",
                label: "Section Intro",
                required: true,
              },
              {
                type: "string",
                name: "ctaLabel",
                label: "CTA Label",
                required: true,
              },
              {
                type: "string",
                name: "ctaHref",
                label: "CTA Link",
                required: true,
              },
              {
                type: "object",
                name: "slides",
                label: "Recipe Cards",
                list: true,
                fields: [
                  {
                    type: "string",
                    name: "title",
                    label: "Recipe Title",
                    required: true,
                  },
                  {
                    type: "image",
                    name: "image",
                    label: "Image",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "imageAlt",
                    label: "Image Alt Text",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "time",
                    label: "Timing",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "difficulty",
                    label: "Difficulty",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredientsLabel",
                    label: "Ingredients Label",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredients",
                    label: "Ingredients",
                    list: true,
                    required: true,
                  },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "recipesSection",
            label: "Recipes Section",
            fields: [
              {
                type: "string",
                name: "title",
                label: "Section Title",
                required: true,
              },
              {
                type: "string",
                name: "intro",
                label: "Section Intro",
                required: true,
              },
              {
                type: "string",
                name: "ctaLabel",
                label: "CTA Label",
                required: true,
              },
              {
                type: "string",
                name: "ctaHref",
                label: "CTA Link",
                required: true,
              },
              {
                type: "object",
                name: "slides",
                label: "Recipe Cards",
                list: true,
                fields: [
                  {
                    type: "string",
                    name: "title",
                    label: "Recipe Title",
                    required: true,
                  },
                  {
                    type: "image",
                    name: "image",
                    label: "Image",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "imageAlt",
                    label: "Image Alt Text",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "time",
                    label: "Timing",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "difficulty",
                    label: "Difficulty",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredientsLabel",
                    label: "Ingredients Label",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredients",
                    label: "Ingredients",
                    list: true,
                    required: true,
                  },
                ],
              },
            ],
          },
          {
            type: "object",
            name: "authorRecipesSection",
            label: "Author Recipes Section",
            fields: [
              {
                type: "string",
                name: "title",
                label: "Section Title",
                required: true,
              },
              {
                type: "string",
                name: "intro",
                label: "Section Intro",
                required: true,
              },
              {
                type: "string",
                name: "ctaLabel",
                label: "CTA Label",
                required: true,
              },
              {
                type: "string",
                name: "ctaHref",
                label: "CTA Link",
                required: true,
              },
              {
                type: "object",
                name: "slides",
                label: "Recipe Cards",
                list: true,
                fields: [
                  {
                    type: "string",
                    name: "title",
                    label: "Recipe Title",
                    required: true,
                  },
                  {
                    type: "image",
                    name: "image",
                    label: "Image",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "imageAlt",
                    label: "Image Alt Text",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "time",
                    label: "Timing",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "difficulty",
                    label: "Difficulty",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredientsLabel",
                    label: "Ingredients Label",
                    required: true,
                  },
                  {
                    type: "string",
                    name: "ingredients",
                    label: "Ingredients",
                    list: true,
                    required: true,
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  search: {
    tina: {
      indexerToken: process.env.TINA_SEARCH_TOKEN,
      stopwordLanguages: ["eng", "spa"],
    },
    indexBatchSize: 100,
    maxSearchIndexFieldLength: 100,
  },
});
